import { StyleSheet } from 'react-native';

/** Layout del wireframe (Mis Tarjetas / espejo receptor). */
export const wireframeLayoutStyles = StyleSheet.create({
  wallpaperFill: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.93,
  },
  wireVerticalCard: {
    borderRadius: 16,
    flex: 1,
    overflow: 'hidden',
  },
  /** Contenido encima del wallpaper (misma idea que web: padding superior bajo el borde de la tarjeta). */
  wireCardContentInset: {
    flex: 1,
    minHeight: 0,
    paddingTop: 12,
  },
  vertHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    gap: 6,
    flexShrink: 0,
  },
  vertBrandingText: {
    fontWeight: '700',
    opacity: 0.85,
  },
  vertTop: {
    flex: 2.9,
    flexDirection: 'column',
    minHeight: 0,
  },
  vertAvatarBox: {
    flex: 1.85,
    paddingHorizontal: 8,
    paddingTop: 4,
    paddingBottom: 10,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  vertInfoBox: {
    flex: 1.55,
    padding: 8,
    paddingTop: 12,
    paddingBottom: 12,
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 5,
  },
  vertName: {
    fontWeight: '800',
    textAlign: 'center',
  },
  vertNick: {
    fontWeight: '600',
    textAlign: 'center',
  },
  vertIconsBox: {
    flex: 2.35,
    marginTop: 12,
    paddingHorizontal: 0,
    paddingTop: 2,
    paddingBottom: 22,
    justifyContent: 'flex-start',
    overflow: 'hidden',
    minHeight: 0,
  },
  wireVertIconGridRoot: {
    justifyContent: 'flex-start',
  },
  wireIconGridRoot: {
    flex: 1,
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    paddingHorizontal: 24,
  },
  wireIconRowsStack: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    width: '100%',
    gap: 12,
  },
  wireIconRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'center',
    width: '100%',
    gap: 12,
    flexWrap: 'nowrap',
    paddingHorizontal: 0,
  },
  wireIconCell: {
    flexGrow: 0,
    flexShrink: 0,
    minWidth: 0,
    alignItems: 'center',
  },
  wireHorizCard: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
  },
  horizHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    gap: 6,
    flexShrink: 0,
  },
  horizBrandingText: {
    fontWeight: '700',
    opacity: 0.85,
  },
  horizMiddleRow: {
    flex: 2.85,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    minHeight: 0,
  },
  horizAvatarBox: {
    flex: 1.2,
    padding: 8,
    paddingRight: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  horizInfoBox: {
    flex: 2.6,
    padding: 8,
    paddingLeft: 4,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  horizName: {
    fontWeight: '800',
    textAlign: 'center',
  },
  horizNick: {
    fontWeight: '600',
    textAlign: 'center',
  },
  horizIconsBox: {
    flex: 2.95,
    marginTop: 12,
    paddingHorizontal: 0,
    paddingTop: 2,
    paddingBottom: 6,
    minHeight: 0,
    overflow: 'hidden',
  },
  wireStatsRowInline: {
    marginTop: 6,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
    width: '100%',
    maxWidth: '100%',
    paddingHorizontal: 2,
  },
  wireStatsRatingStack: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    flex: 1,
    minWidth: 0,
  },
  wireStatsReviewCaption: {
    fontWeight: '600',
    flexShrink: 1,
  },
  wireUsersPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#AFCFE6',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  wireUsersPillText: {
    color: '#071226',
    fontSize: 10,
    fontWeight: '800',
  },
});
