/**
 * Tema global Día/Noche — cascarón dinámico alineado con `premiumTheme`.
 * `background` / `motherBg` usan translucidez para el gradiente de Tabs.
 * Colores base: `styles/_premiumTheme` (light/dark).
 */

import { premiumTheme as PT } from '@/styles/_premiumTheme';

const pl = PT.light;
const pd = PT.dark;

const light = {
  motherBg: pl.backgroundTranslucent,
  primaryText: pl.text,
  iconColor: pl.text,
  headerDivider: pl.accent,
  progressTrack: 'rgba(28,28,30,0.12)',
  progressFill: pl.focus,
  gridCardBg: 'rgba(28,28,30,0.06)',
  iconCircleBg: pl.surface,
  gridCardBorder: 'rgba(212,175,55,0.45)',
  secondaryText: pl.textSecondary,
  viewerFallbackText: pl.text,
  contextMenuBg: pl.surfaceElevated,
  contextMenuBorder: pl.accent,
  contextMenuText: pl.text,
  contextDeleteDivider: 'rgba(28,28,30,0.08)',
  floatingCardBg: pl.surfaceElevated,
  floatingCardBorder: pl.border,
  floatingTitle: pl.text,
  floatingBody: pl.muted,
  floatingCopyBg: pl.surface,
  floatingCopyText: pl.text,
  floatingCloseBg: pl.surface,
  floatingCloseText: pl.text,
  selectedActionBg: pl.accent,
  selectedActionText: pl.onVipBanner,
  selectedActionGlow: pl.accent,
  searchBg: pl.surfaceElevated,
  searchBorder: pl.border,
  searchText: pl.text,
  searchPlaceholder: pl.muted,
  typeBadgeBg: 'rgba(212,175,55,0.14)',
  typeBadgeText: pl.accentPressed,
  counterAccent: pl.accent,
  refreshTint: pl.accent,
  emptyCtaBg: pl.accent,
  emptyCtaText: pl.onAccent,
  viewerDownloadBg: pl.accent,
  viewerDownloadLabel: pl.text,
  viewerIconTint: pl.text,
  viewerCloseTint: pl.text,
  viewerCloseButtonBg: 'rgba(28,28,30,0.08)',

  background: pl.backgroundTranslucent,
  backgroundSolid: pl.background,
  text: pl.text,
  textPrimary: pl.text,
  textSecondary: pl.textSecondary,
  textMuted: pl.muted,
  sectionLabel: pl.text,
  tint: pl.accent,
  divider: pl.accent,
  icon: pl.text,
  fabBg: pl.text,
  fabText: pl.onVipBanner,
  modalOverlay: pl.overlay,
  modalBg: pl.surfaceElevated,
  modalBorder: pl.border,
  modalTitle: pl.text,
  modalSubtitle: pl.textSecondary,
  btnPrimary: pl.text,
  btnPrimaryText: pl.onVipBanner,
  btnGhost: pl.surface,
  btnGhostText: pl.text,
  inputBg: pl.surfaceElevated,
  inputText: pl.text,
  overlay: 'rgba(242,242,247,0.92)',
  modalRowBg: pl.surfaceElevated,
  modalRowBorder: pl.divider,

  surface: pl.surfaceElevated,
  surfaceMuted: 'rgba(255,255,255,0.88)',
  border: pl.border,
  ctaPrimary: pl.text,
  ctaAccent: pl.accent,
  overlayScrim: 'rgba(15,20,25,0.38)',
  emptyIconMuted: pl.muted,
  refreshAccent: pl.focus,

  avatarFallbackBg: pl.surface,
  avatarFallbackBorder: pl.divider,
  pillBg: 'rgba(255,255,255,0.9)',
  pillBorder: pl.border,
  pillText: pl.text,
  filterPillBg: pl.surface,
  utilBtnBg: pl.surfaceElevated,
  utilBtnBorder: pl.accent,
  scanFabBg: pl.text,
  scanFabIcon: pl.onVipBanner,

  callsCardBg: 'rgba(255,255,255,0.94)',
  callsCardBorder: pl.border,
  textChannel: pl.textSecondary,
  headerBtnBg: pl.text,
  voiceBtnBg: pl.text,
  loaderAccent: pl.text,

  storiesGlowGradient: ['rgba(212,175,55,0.22)', 'rgba(184,150,46,0.14)', 'rgba(28,28,30,0.08)'] as const,
  storiesGlowInnerBg: 'rgba(255,255,255,0.72)',
  storiesGlowInnerBorder: 'rgba(212,175,55,0.35)',
  storiesNormalBtnBg: 'rgba(52,199,89,0.12)',
  storiesNormalBtnBorder: 'rgba(52,199,89,0.35)',
  storiesOffBtnBg: pl.surfaceElevated,
  storiesOffBtnBorder: pl.divider,
  storiesCreateCardBg: pl.surface,
  storiesCreateCardBorder: pl.border,
  storiesModalOverlayBg: 'rgba(15,20,25,0.45)',
  storiesFabHalo: 'rgba(212,175,55,0.25)',
  storiesFabBorder: pl.accent,
  storiesControlActiveBg: pl.surface,
  storiesControlActiveBorder: pl.accent,
  storiesCancelBtnBg: pl.surface,
  storiesPublishDisabled: pl.muted,

  success: pl.success,
  danger: pl.danger,
  favoriteActive: '#B7343A',
  marketVipCardBg: pl.surfaceElevated,
  marketVipCardBorder: pl.divider,
  marketVipCtaDivider: pl.divider,
  marketVipQrFg: pl.text,
  marketVipQrBg: pl.surfaceElevated,
  marketVipTitle: pl.text,
  marketVipBody: pl.muted,
  marketDullCardBg: pl.surface,
  marketDullCardBorder: pl.border,
  marketDullQrWrapBg: pl.surface,
  marketDullPillBg: pl.accentDisabled,
  marketDullPillText: pl.muted,
  marketExportBtnBg: pl.text,
  marketCtaPressedBg: 'rgba(0,122,255,0.12)',
  avatarPlaceholderBg: pl.surface,
  subtleShadow: 'rgba(0,0,0,0.35)',
  brandShadow: 'rgba(28,28,30,0.25)',
  loadingOverlayDim: 'rgba(255,255,255,0.5)',
  loadingOverlayDimDark: 'rgba(0,0,0,0.3)',
  tabShellGradient: pl.tabShellGradient,
  luxuryFrameGradient: pl.luxuryFrameGradient,
  luxuryCtaGradient: pl.luxuryCtaGradient,
  vipBannerGradient: pl.vipBannerGradient,
  vipBannerChevron: pl.vipBannerChevron,
  vipBannerDiamondIcon: pl.vipBannerIcon,
  wireframeIconMuted: pl.muted,
  dangerBannerBg: pl.dangerMuted,
  dangerBannerBorder: 'rgba(255,59,48,0.35)',
  dangerBannerBgDark: 'rgba(255,59,48,0.12)',
  dangerBannerBorderDark: 'rgba(255,69,58,0.35)',
  swipeDeleteBg: '#6B1D1D',
  swipeStripEditBg: '#3A3D42',
  subscriberSwipeMuteBg: '#1E3A5F',
  subscriberSwipeRevokeBg: '#5C3D1E',
  callsShellGradient: ['#F2F2F7', '#E8E8ED', pl.background] as const,
  /** Ghost-Link VoIP pantalla completa (siempre cinemática oscura). */
  ghostLinkPremiumGradient: ['#030814', '#0A1E38', '#0F2F58'] as const,
  ghostLinkOnGradient: '#FFFFFF',
} as const;

const dark = {
  motherBg: pd.backgroundTranslucent,
  primaryText: pd.text,
  iconColor: pd.text,
  headerDivider: pd.accent,
  progressTrack: 'rgba(255,255,255,0.14)',
  progressFill: pd.focus,
  gridCardBg: 'rgba(255,255,255,0.06)',
  iconCircleBg: pd.surface,
  gridCardBorder: 'rgba(212,175,55,0.22)',
  secondaryText: pd.textSecondary,
  viewerFallbackText: pd.text,
  contextMenuBg: pd.surfaceElevated,
  contextMenuBorder: pd.accent,
  contextMenuText: pd.text,
  contextDeleteDivider: 'rgba(255,255,255,0.1)',
  floatingCardBg: pd.surfaceElevated,
  floatingCardBorder: pd.border,
  floatingTitle: pd.text,
  floatingBody: pd.textSecondary,
  floatingCopyBg: pd.surface,
  floatingCopyText: pd.text,
  floatingCloseBg: pd.surface,
  floatingCloseText: pd.text,
  selectedActionBg: pd.accent,
  selectedActionText: pd.onVipBanner,
  selectedActionGlow: pd.accent,
  searchBg: pd.surface,
  searchBorder: pd.border,
  searchText: pd.text,
  searchPlaceholder: pd.muted,
  typeBadgeBg: 'rgba(212,175,55,0.18)',
  typeBadgeText: pd.accent,
  counterAccent: pd.accent,
  refreshTint: pd.accent,
  emptyCtaBg: pd.accent,
  emptyCtaText: pd.onAccent,
  viewerDownloadBg: pd.accent,
  viewerDownloadLabel: pd.onAccent,
  viewerIconTint: pd.onAccent,
  viewerCloseTint: pd.text,
  viewerCloseButtonBg: 'rgba(255,255,255,0.12)',

  background: pd.backgroundTranslucent,
  backgroundSolid: pd.background,
  text: pd.text,
  textPrimary: pd.text,
  textSecondary: pd.textSecondary,
  textMuted: pd.muted,
  sectionLabel: pd.textSecondary,
  tint: pd.accent,
  divider: pd.accent,
  icon: pd.textSecondary,
  fabBg: pd.surfaceElevated,
  fabText: pd.text,
  modalOverlay: pd.overlay,
  modalBg: pd.surfaceElevated,
  modalBorder: pd.border,
  modalTitle: pd.text,
  modalSubtitle: pd.textSecondary,
  btnPrimary: pd.accent,
  btnPrimaryText: pd.onAccent,
  btnGhost: pd.surface,
  btnGhostText: pd.textSecondary,
  inputBg: pd.surface,
  inputText: pd.text,
  overlay: 'rgba(0,0,0,0.88)',
  modalRowBg: pd.surface,
  modalRowBorder: pd.border,

  surface: pd.surfaceElevated,
  surfaceMuted: pd.surface,
  border: pd.border,
  ctaPrimary: pd.accent,
  ctaAccent: pd.accent,
  overlayScrim: pd.overlay,
  emptyIconMuted: pd.muted,
  refreshAccent: pd.focus,

  avatarFallbackBg: pd.surface,
  avatarFallbackBorder: pd.border,
  pillBg: 'rgba(44,44,46,0.92)',
  pillBorder: pd.border,
  pillText: pd.textSecondary,
  filterPillBg: 'rgba(28,28,30,0.85)',
  utilBtnBg: pd.surface,
  utilBtnBorder: pd.accent,
  scanFabBg: pd.accent,
  scanFabIcon: pd.onAccent,

  callsCardBg: 'rgba(44,44,46,0.94)',
  callsCardBorder: pd.border,
  textChannel: pd.textSecondary,
  headerBtnBg: pd.accent,
  voiceBtnBg: pd.accent,
  loaderAccent: pd.accent,

  storiesGlowGradient: ['rgba(212,175,55,0.28)', 'rgba(201,162,39,0.18)', 'rgba(10,8,4,0.5)'] as const,
  storiesGlowInnerBg: 'rgba(44,44,46,0.9)',
  storiesGlowInnerBorder: 'rgba(212,175,55,0.35)',
  storiesNormalBtnBg: 'rgba(48,209,88,0.14)',
  storiesNormalBtnBorder: 'rgba(48,209,88,0.35)',
  storiesOffBtnBg: 'rgba(28,28,30,0.75)',
  storiesOffBtnBorder: pd.border,
  storiesCreateCardBg: pd.surface,
  storiesCreateCardBorder: pd.border,
  storiesModalOverlayBg: 'rgba(0,0,0,0.65)',
  storiesFabHalo: 'rgba(212,175,55,0.22)',
  storiesFabBorder: pd.accent,
  storiesControlActiveBg: 'rgba(212,175,55,0.18)',
  storiesControlActiveBorder: pd.accent,
  storiesCancelBtnBg: pd.surface,
  storiesPublishDisabled: pd.muted,

  success: pd.success,
  danger: pd.danger,
  favoriteActive: '#B7343A',
  marketVipCardBg: pl.surfaceElevated,
  marketVipCardBorder: pl.divider,
  marketVipCtaDivider: pl.divider,
  marketVipQrFg: pl.text,
  marketVipQrBg: pl.surfaceElevated,
  marketVipTitle: pl.text,
  marketVipBody: pl.muted,
  marketDullCardBg: pl.surface,
  marketDullCardBorder: pl.border,
  marketDullQrWrapBg: pl.surface,
  marketDullPillBg: pl.accentDisabled,
  marketDullPillText: pl.muted,
  marketExportBtnBg: pl.text,
  marketCtaPressedBg: 'rgba(10,132,255,0.18)',
  avatarPlaceholderBg: 'rgba(255,255,255,0.1)',
  subtleShadow: '#000000',
  brandShadow: 'rgba(0,0,0,0.45)',
  loadingOverlayDim: 'rgba(255,255,255,0.45)',
  loadingOverlayDimDark: 'rgba(0,0,0,0.35)',
  tabShellGradient: pd.tabShellGradient,
  luxuryFrameGradient: pd.luxuryFrameGradient,
  luxuryCtaGradient: pd.luxuryCtaGradient,
  vipBannerGradient: pd.vipBannerGradient,
  vipBannerChevron: pd.vipBannerChevron,
  vipBannerDiamondIcon: pd.vipBannerIcon,
  wireframeIconMuted: pd.muted,
  dangerBannerBg: pd.dangerMuted,
  dangerBannerBorder: 'rgba(255,69,58,0.4)',
  dangerBannerBgDark: 'rgba(255,69,58,0.16)',
  dangerBannerBorderDark: 'rgba(255,69,58,0.4)',
  swipeDeleteBg: '#7A2029',
  swipeStripEditBg: '#2A2D35',
  subscriberSwipeMuteBg: '#1A3350',
  subscriberSwipeRevokeBg: '#4A3020',
  callsShellGradient: ['#1C1C1E', '#0F0F10', pd.background] as const,
  ghostLinkPremiumGradient: ['#030814', '#0A1E38', '#0F2F58'] as const,
  ghostLinkOnGradient: '#FFFFFF',
} as const;

const palette = {
  light,
  dark,
};

/** Tema del cascarón dinámico (día o noche); unión para props que reciben `palette.light` o `palette.dark`. */
export type AppShellTheme = (typeof palette)['light'] | (typeof palette)['dark'];
export default palette;
