/**
 * Tema global Día/Noche — cascarón dinámico alineado con `premiumTheme`.
 * `background` / `motherBg` usan translucidez para el gradiente de Tabs.
 * Colores base: `styles/_premiumTheme` (light/dark).
 */

import { premiumTheme as PT } from '@/styles/_premiumTheme';

const pl = PT.light;
const pd = PT.dark;

const light = {
  motherBg: pl.backgroundTranslucent,
  primaryText: pl.text,
  iconColor: pl.text,
  headerDivider: pl.accent,
  progressTrack: 'rgba(28,28,30,0.12)',
  progressFill: pl.focus,
  gridCardBg: '#FFFFFF',
  iconCircleBg: pl.surface,
  gridCardBorder: 'rgba(233,195,73,0.45)',
  secondaryText: pl.textSecondary,
  viewerFallbackText: pl.text,
  contextMenuBg: pl.surfaceElevated,
  contextMenuBorder: pl.accent,
  contextMenuText: pl.text,
  contextDeleteDivider: 'rgba(28,28,30,0.08)',
  floatingCardBg: pl.surfaceElevated,
  floatingCardBorder: pl.border,
  floatingTitle: pl.text,
  floatingBody: pl.muted,
  floatingCopyBg: pl.surface,
  floatingCopyText: pl.text,
  floatingCloseBg: pl.surface,
  floatingCloseText: pl.text,
  selectedActionBg: pl.accent,
  selectedActionText: pl.onVipBanner,
  selectedActionGlow: pl.accent,
  searchBg: pl.surfaceElevated,
  searchBorder: pl.border,
  searchText: pl.text,
  searchPlaceholder: pl.muted,
  typeBadgeBg: 'rgba(233,195,73,0.14)',
  typeBadgeText: pl.accentPressed,
  counterAccent: pl.accent,
  refreshTint: pl.accent,
  emptyCtaBg: pl.accent,
  emptyCtaText: pl.onAccent,
  viewerDownloadBg: pl.accent,
  viewerDownloadLabel: pl.text,
  viewerIconTint: pl.text,
  viewerCloseTint: pl.text,
  viewerCloseButtonBg: 'rgba(28,28,30,0.08)',

  background: pl.backgroundTranslucent,
  backgroundSolid: pl.background,
  text: pl.text,
  textPrimary: pl.text,
  textSecondary: pl.textSecondary,
  textMuted: pl.muted,
  sectionLabel: pl.text,
  tint: pl.accent,
  divider: pl.accent,
  icon: pl.text,
  fabBg: pl.accent,
  fabText: pl.onAccent,
  modalOverlay: pl.overlay,
  modalBg: pl.surfaceElevated,
  modalBorder: pl.border,
  modalTitle: pl.text,
  modalSubtitle: pl.textSecondary,
  btnPrimary: pl.accent,
  btnPrimaryText: pl.onAccent,
  btnGhost: pl.surface,
  btnGhostText: pl.text,
  inputBg: pl.surfaceElevated,
  inputText: pl.text,
  overlay: 'rgba(0,0,0,0.5)',
  modalRowBg: pl.surfaceElevated,
  modalRowBorder: pl.divider,

  surface: pl.surfaceElevated,
  surfaceMuted: '#FFFFFF',
  border: pl.border,
  ctaPrimary: pl.accent,
  ctaAccent: pl.accent,
  overlayScrim: 'rgba(0,0,0,0.5)',
  emptyIconMuted: pl.muted,
  refreshAccent: pl.focus,

  avatarFallbackBg: pl.surface,
  avatarFallbackBorder: pl.divider,
  pillBg: '#FFFFFF',
  pillBorder: pl.border,
  pillText: pl.text,
  filterPillBg: pl.surface,
  utilBtnBg: pl.surfaceElevated,
  utilBtnBorder: pl.accent,
  scanFabBg: pl.accent,
  scanFabIcon: pl.onAccent,

  callsCardBg: '#FFFFFF',
  callsCardBorder: pl.border,
  /** Texto secundario/muted sobre tarjetas Calls (evitar gris oscuro sobre gris en noche). */
  callsOnCardSecondary: pl.textSecondary,
  callsOnCardMuted: pl.muted,
  textChannel: pl.textSecondary,
  headerBtnBg: pl.accent,
  voiceBtnBg: pl.accent,
  loaderAccent: pl.accent,

  success: pl.success,
  danger: pl.danger,
  favoriteActive: '#B7343A',
  marketVipCardBg: pl.surfaceElevated,
  marketVipCardBorder: pl.divider,
  marketVipCtaDivider: pl.divider,
  marketVipQrFg: pl.text,
  marketVipQrBg: pl.surfaceElevated,
  marketVipTitle: pl.text,
  marketVipBody: pl.muted,
  marketDullCardBg: pl.surface,
  marketDullCardBorder: pl.border,
  marketDullQrWrapBg: pl.surface,
  marketDullPillBg: pl.accentDisabled,
  marketDullPillText: pl.muted,
  marketExportBtnBg: pl.text,
  marketCtaPressedBg: 'rgba(233,195,73,0.14)',
  avatarPlaceholderBg: pl.surface,
  subtleShadow: 'rgba(0,0,0,0.35)',
  brandShadow: 'rgba(28,28,30,0.25)',
  loadingOverlayDim: 'rgba(255,255,255,0.5)',
  loadingOverlayDimDark: 'rgba(0,0,0,0.3)',
  tabShellGradient: pl.tabShellGradient,
  luxuryFrameGradient: pl.luxuryFrameGradient,
  luxuryCtaGradient: pl.luxuryCtaGradient,
  vipBannerGradient: pl.vipBannerGradient,
  vipBannerChevron: pl.vipBannerChevron,
  vipBannerDiamondIcon: pl.vipBannerIcon,
  wireframeIconMuted: pl.muted,
  dangerBannerBg: pl.dangerMuted,
  dangerBannerBorder: 'rgba(255,59,48,0.35)',
  dangerBannerBgDark: 'rgba(255,59,48,0.12)',
  dangerBannerBorderDark: 'rgba(255,69,58,0.35)',
  swipeDeleteBg: '#6B1D1D',
  swipeStripEditBg: '#3A3D42',
  subscriberSwipeMuteBg: '#1E3A5F',
  subscriberSwipeRevokeBg: '#5C3D1E',
  callsShellGradient: ['#F2F2F7', '#F2F2F7', '#F2F2F7'] as const,
  /** Ghost-Link: fondo pantalla completa (modo día, alineado al cascarón premium). */
  ghostLinkPremiumGradient: ['#F2F2F7', '#F2F2F7', '#F2F2F7'] as const,
  /** Texto/icono principal sobre el fondo Ghost-Link (día: oscuro). */
  ghostLinkOnGradient: pl.text,
  ghostLinkTextPrimary: pl.text,
  ghostLinkTextSecondary: pl.textSecondary,
  ghostLinkTextMuted: pl.muted,
  ghostLinkLogoBubbleBg: '#F5F0E6',
  ghostLinkLogoBubbleBorder: 'rgba(233, 195, 73, 0.42)',
  ghostLinkAvatarInnerBg: '#FFFFFF',
  ghostLinkControlFrost: 'rgba(28, 28, 30, 0.08)',
  ghostLinkControlFrostActive: 'rgba(233, 195, 73, 0.24)',
  /** Full-bleed vídeo Ghost-Link: base cinematográfica (texto claro encima). */
  ghostLinkVideoStageBg: 'rgba(22, 27, 34, 0.98)',
  ghostLinkRemoteVideoPlaceholderBg: 'rgba(30, 36, 44, 0.92)',
  ghostLinkRingingVideoScrim: 'rgba(15, 20, 25, 0.42)',
  ghostLinkVideoTopBarText: 'rgba(255, 255, 255, 0.95)',
  ghostLinkVideoTopBarMuted: 'rgba(255, 255, 255, 0.65)',
  ghostLinkVideoWaitingText: 'rgba(255, 255, 255, 0.55)',
  ghostLinkOnHangup: '#FFFFFF',
  ghostLinkVideoPipShadow: 'rgba(28, 28, 30, 0.35)',
  /** Controles sobre el stage de vídeo (fondo oscuro en ambos modos sistema). */
  ghostLinkVideoControlFrost: 'rgba(255, 255, 255, 0.18)',
  ghostLinkVideoControlFrostActive: 'rgba(255, 255, 255, 0.32)',
  ghostLinkVideoControlIcon: 'rgba(255, 255, 255, 0.95)',
  ghostLinkVideoControlLabel: 'rgba(255, 255, 255, 0.78)',
} as const;

const dark = {
  motherBg: pd.backgroundTranslucent,
  primaryText: pd.text,
  iconColor: pd.text,
  headerDivider: pd.accent,
  progressTrack: 'rgba(255,255,255,0.14)',
  progressFill: pd.focus,
  gridCardBg: '#1C1C1E',
  iconCircleBg: pd.surface,
  gridCardBorder: 'rgba(233,195,73,0.22)',
  secondaryText: pd.textSecondary,
  viewerFallbackText: pd.text,
  contextMenuBg: pd.surfaceElevated,
  contextMenuBorder: pd.accent,
  contextMenuText: pd.text,
  contextDeleteDivider: 'rgba(255,255,255,0.1)',
  floatingCardBg: pd.surfaceElevated,
  floatingCardBorder: pd.border,
  floatingTitle: pd.text,
  floatingBody: pd.textSecondary,
  floatingCopyBg: pd.surface,
  floatingCopyText: pd.text,
  floatingCloseBg: pd.surface,
  floatingCloseText: pd.text,
  selectedActionBg: pd.accent,
  selectedActionText: pd.onVipBanner,
  selectedActionGlow: pd.accent,
  searchBg: pd.surface,
  searchBorder: pd.border,
  searchText: pd.text,
  searchPlaceholder: pd.muted,
  typeBadgeBg: 'rgba(233,195,73,0.18)',
  typeBadgeText: pd.accent,
  counterAccent: pd.accent,
  refreshTint: pd.accent,
  emptyCtaBg: pd.accent,
  emptyCtaText: pd.onAccent,
  viewerDownloadBg: pd.accent,
  viewerDownloadLabel: pd.onAccent,
  viewerIconTint: pd.onAccent,
  viewerCloseTint: pd.text,
  viewerCloseButtonBg: 'rgba(255,255,255,0.12)',

  background: pd.backgroundTranslucent,
  backgroundSolid: pd.background,
  text: pd.text,
  textPrimary: pd.text,
  textSecondary: pd.textSecondary,
  textMuted: pd.muted,
  sectionLabel: pd.textSecondary,
  tint: pd.accent,
  divider: pd.accent,
  icon: pd.textSecondary,
  fabBg: pd.accent,
  fabText: pd.onAccent,
  modalOverlay: pd.overlay,
  modalBg: pd.surfaceElevated,
  modalBorder: pd.border,
  modalTitle: pd.text,
  modalSubtitle: pd.textSecondary,
  btnPrimary: pd.accent,
  btnPrimaryText: pd.onAccent,
  btnGhost: pd.surface,
  btnGhostText: pd.textSecondary,
  inputBg: pd.surface,
  inputText: pd.text,
  overlay: 'rgba(0,0,0,0.55)',
  modalRowBg: pd.surface,
  modalRowBorder: pd.border,

  surface: pd.surfaceElevated,
  surfaceMuted: pd.surface,
  border: pd.border,
  ctaPrimary: pd.accent,
  ctaAccent: pd.accent,
  overlayScrim: pd.overlay,
  emptyIconMuted: pd.muted,
  refreshAccent: pd.focus,

  avatarFallbackBg: pd.surface,
  avatarFallbackBorder: pd.border,
  pillBg: '#1C1C1E',
  pillBorder: pd.border,
  pillText: pd.textSecondary,
  filterPillBg: '#1C1C1E',
  utilBtnBg: pd.surface,
  utilBtnBorder: pd.accent,
  scanFabBg: pd.accent,
  scanFabIcon: pd.onAccent,

  callsCardBg: '#1C1C1E',
  callsCardBorder: pd.border,
  /** Sobre fondo oscuro: tonos claros translúcidos (WCAG frente a gris #2C2C2E). */
  callsOnCardSecondary: 'rgba(235, 235, 245, 0.78)',
  callsOnCardMuted: 'rgba(235, 235, 245, 0.58)',
  textChannel: pd.textSecondary,
  headerBtnBg: pd.accent,
  voiceBtnBg: pd.accent,
  loaderAccent: pd.accent,

  success: pd.success,
  danger: pd.danger,
  favoriteActive: '#B7343A',
  marketVipCardBg: pd.surfaceElevated,
  marketVipCardBorder: pd.border,
  marketVipCtaDivider: pd.border,
  marketVipQrFg: pd.text,
  marketVipQrBg: pd.surfaceElevated,
  marketVipTitle: pd.text,
  marketVipBody: pd.muted,
  marketDullCardBg: pd.surface,
  marketDullCardBorder: pd.border,
  marketDullQrWrapBg: pd.surface,
  marketDullPillBg: pd.accentDisabled,
  marketDullPillText: pd.muted,
  marketExportBtnBg: pd.text,
  marketCtaPressedBg: 'rgba(233,195,73,0.18)',
  avatarPlaceholderBg: '#1C1C1E',
  subtleShadow: '#000000',
  brandShadow: 'rgba(0,0,0,0.45)',
  loadingOverlayDim: 'rgba(255,255,255,0.45)',
  loadingOverlayDimDark: 'rgba(0,0,0,0.35)',
  tabShellGradient: pd.tabShellGradient,
  luxuryFrameGradient: pd.luxuryFrameGradient,
  luxuryCtaGradient: pd.luxuryCtaGradient,
  vipBannerGradient: pd.vipBannerGradient,
  vipBannerChevron: pd.vipBannerChevron,
  vipBannerDiamondIcon: pd.vipBannerIcon,
  wireframeIconMuted: pd.muted,
  dangerBannerBg: pd.dangerMuted,
  dangerBannerBorder: 'rgba(255,69,58,0.4)',
  dangerBannerBgDark: 'rgba(255,69,58,0.16)',
  dangerBannerBorderDark: 'rgba(255,69,58,0.4)',
  swipeDeleteBg: '#7A2029',
  swipeStripEditBg: '#2A2D35',
  subscriberSwipeMuteBg: '#1A3350',
  subscriberSwipeRevokeBg: '#4A3020',
  callsShellGradient: ['#000000', '#000000', '#000000'] as const,
  /** Ghost-Link: fondo nocturno (cinemático, contraste alto). */
  ghostLinkPremiumGradient: ['#000000', '#000000', '#000000'] as const,
  ghostLinkOnGradient: '#FFFFFF',
  ghostLinkTextPrimary: '#FFFFFF',
  ghostLinkTextSecondary: 'rgba(255, 255, 255, 0.74)',
  ghostLinkTextMuted: 'rgba(255, 255, 255, 0.52)',
  ghostLinkLogoBubbleBg: '#F5F0E6',
  ghostLinkLogoBubbleBorder: 'rgba(233, 195, 73, 0.5)',
  ghostLinkAvatarInnerBg: '#1C1C1E',
  ghostLinkControlFrost: 'rgba(255, 255, 255, 0.15)',
  ghostLinkControlFrostActive: 'rgba(255, 255, 255, 0.35)',
  ghostLinkVideoStageBg: 'rgba(4, 8, 14, 0.99)',
  ghostLinkRemoteVideoPlaceholderBg: 'rgba(10, 16, 28, 0.94)',
  ghostLinkRingingVideoScrim: 'rgba(0, 0, 0, 0.36)',
  ghostLinkVideoTopBarText: 'rgba(255, 255, 255, 0.95)',
  ghostLinkVideoTopBarMuted: 'rgba(255, 255, 255, 0.65)',
  ghostLinkVideoWaitingText: 'rgba(255, 255, 255, 0.55)',
  ghostLinkOnHangup: '#FFFFFF',
  ghostLinkVideoPipShadow: 'rgba(0, 0, 0, 0.45)',
  ghostLinkVideoControlFrost: 'rgba(255, 255, 255, 0.18)',
  ghostLinkVideoControlFrostActive: 'rgba(255, 255, 255, 0.32)',
  ghostLinkVideoControlIcon: 'rgba(255, 255, 255, 0.95)',
  ghostLinkVideoControlLabel: 'rgba(255, 255, 255, 0.78)',
} as const;

const palette = {
  light,
  dark,
};

/** Tema del cascarón dinámico (día o noche); unión para props que reciben `palette.light` o `palette.dark`. */
export type AppShellTheme = (typeof palette)['light'] | (typeof palette)['dark'];
export default palette;
