import { Platform, StyleSheet } from "react-native";
import type { AppShellTheme } from "../theme";

export function makeContactsStyles(shell: AppShellTheme) {
  return StyleSheet.create({
  container: {
    flex: 1,
  },
  headerBar: {
    paddingTop: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    color: shell.textPrimary,
    fontSize: 23,
    fontFamily: 'Georgia',
    fontWeight: '800',
    letterSpacing: 0.25,
  },
  scanBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: shell.refreshAccent,
    borderRadius: 999,
    paddingHorizontal: 10,
    height: 40,
  },
  scanBtnText: {
    color: shell.btnPrimaryText,
    fontSize: 12,
    fontWeight: '700',
  },
  toolbarRow: {
    marginTop: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  searchWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surfaceMuted,
    paddingHorizontal: 12,
    height: 44,
  },
  searchInput: {
    flex: 1,
    color: shell.textPrimary,
    fontSize: 13.5,
  },
  sortBtn: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surface,
    height: 44,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: shell.textPrimary,
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  sortBtnText: {
    color: shell.textPrimary,
    fontWeight: '700',
    fontSize: 12.5,
  },
  activeSortPillWrap: {
    paddingHorizontal: 16,
    marginTop: 9,
  },
  activeSortPill: {
    alignSelf: 'flex-start',
    color: shell.textPrimary,
    fontSize: 11.5,
    fontWeight: '700',
    borderRadius: 999,
    backgroundColor: shell.surfaceMuted,
    paddingHorizontal: 11,
    paddingVertical: 6.5,
  },
  listAnimatedWrap: {
    flex: 1,
    width: '100%',
    alignSelf: 'stretch',
  },
  contactSwipeRow: {
    width: '100%',
  },
  centerWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  skeletonListWrap: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
  },
  emptyListRoot: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingBottom: 40,
  },
  emptyListTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginTop: 16,
    textAlign: 'center',
  },
  emptyListSubtitle: {
    fontSize: 14,
    marginTop: 10,
    textAlign: 'center',
    lineHeight: 20,
  },
  listContainer: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 28,
  },
  emptyText: {
    color: shell.textSecondary,
    textAlign: 'center',
    marginTop: 40,
    fontSize: 13,
  },
  groupHeaderWrap: {
    width: '100%',
    paddingHorizontal: 8,
    paddingVertical: 7,
    marginTop: 9,
  },
  groupHeaderText: {
    color: shell.textPrimary,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  contactThemedSurface: {
    width: '100%',
    marginBottom: 8,
    shadowColor: shell.textPrimary,
    shadowOpacity: 0.09,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  contactCardInnerThemed: {
    position: 'relative',
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 101,
  },
  contactCardMuted: {
    opacity: 0.92,
  },
  channelMutedBadge: {
    position: 'absolute',
    top: 8,
    right: 10,
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
  },
  channelMutedBadgeText: {
    fontSize: 10,
    fontWeight: '800',
  },
  contactCardBody: {
    flex: 1,
    minWidth: 0,
  },
  contactTitleName: {
    fontSize: 15,
    fontWeight: '800',
    lineHeight: 19,
  },
  contactOccupationLine: {
    marginTop: 2,
    lineHeight: 16,
  },
  contactSubtitleCardName: {
    marginTop: 3,
    fontSize: 12,
    fontWeight: '600',
  },
  /** Fila 3: valoración (izq.) + pastilla mutuales (der.), misma línea que el mock. */
  contactRowStatsRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: 6,
  },
  contactRowRatingCluster: {
    alignItems: 'flex-start',
    flexShrink: 1,
    minWidth: 0,
  },
  contactRatingCaption: {
    marginTop: 2,
    fontSize: 9,
    fontWeight: '700',
  },
  mutualCountPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  mutualCountPillText: {
    fontSize: 10,
    fontWeight: '800',
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  avatarLg: {
    width: 73,
    height: 73,
    borderRadius: 36.5,
  },
  avatarRingLg: {
    width: 81,
    height: 81,
    borderRadius: 40.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarFallbackLg: {
    width: 73,
    height: 73,
    borderRadius: 36.5,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  avatarRing: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarRingNone: {
    borderWidth: 0,
    borderColor: 'transparent',
  },
  avatarFallback: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  contactName: {
    color: shell.textPrimary,
    fontSize: 13.5,
    fontWeight: '800',
    maxWidth: '52%',
  },
  contactNick: {
    color: shell.textSecondary,
    fontSize: 10.5,
    fontWeight: '700',
    maxWidth: '42%',
  },
  cardNameText: {
    marginTop: 2,
    color: shell.textSecondary,
    fontSize: 11.5,
    fontWeight: '600',
  },
  metaRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
  },
  ratingNumber: {
    color: shell.textPrimary,
    fontSize: 11,
    fontWeight: '800',
  },
  ratingNumberAlert: {
    color: shell.danger,
  },
  holdersPill: {
    marginLeft: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surfaceMuted,
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  holdersPillText: {
    color: shell.textPrimary,
    fontSize: 10,
    fontWeight: '700',
  },
  rowTrashBtn: {
    width: 34,
    height: 34,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: shell.refreshAccent,
    shadowColor: shell.refreshAccent,
    shadowOpacity: 0.2,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(7,33,54,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  sortModalCard: {
    width: '92%',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surfaceMuted,
    padding: 14,
  },
  sortModalTitle: {
    color: shell.textPrimary,
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 9,
  },
  sortOptionRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surface,
    paddingHorizontal: 11,
    paddingVertical: 10,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sortOptionRowActive: {
    borderColor: shell.textPrimary,
    backgroundColor: shell.surfaceMuted,
  },
  sortOptionText: {
    color: shell.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  sortOptionTextActive: {
    color: shell.textPrimary,
  },
  actionModalCard: {
    width: '90%',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surfaceMuted,
    padding: 14,
  },
  actionModalTitle: {
    color: shell.textPrimary,
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 10,
  },
  actionRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surface,
    paddingHorizontal: 11,
    paddingVertical: 10,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  actionText: {
    color: shell.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  actionRowDanger: {
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 10,
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  actionTextDanger: {
    fontSize: 13,
    fontWeight: '800',
  },
  groupPickerCard: {
    width: '90%',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surfaceMuted,
    padding: 14,
  },
  groupRowWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  groupSelectRow: {
    flex: 1,
    marginBottom: 0,
  },
  groupFavBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  groupFavBtnActive: {
    borderColor: shell.ctaAccent,
    backgroundColor: 'rgba(197,160,101,0.14)',
  },
  newGroupWrap: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  newGroupInput: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surface,
    color: shell.textPrimary,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 13,
  },
  newGroupBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: shell.textPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingCard: {
    width: '90%',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: 'rgba(242,251,255,0.94)',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  /** Contenedor del preview tipo teatro (ThemedSharedCardSurface). */
  floatingTheaterOuter: {
    width: '90%',
    maxWidth: 400,
    alignSelf: 'center',
  },
  floatingTheaterSurface: {
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 20,
    position: 'relative',
    overflow: 'hidden',
  },
  closeBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: shell.surfaceMuted,
  },
  modalAvatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
  },
  modalAvatarFallback: {
    width: 84,
    height: 84,
    borderRadius: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surfaceMuted,
  },
  modalName: {
    marginTop: 10,
    color: shell.textPrimary,
    fontSize: 19,
    fontWeight: '800',
  },
  modalNick: {
    marginTop: 3,
    color: shell.textSecondary,
    fontSize: 12,
  },
  modalCardName: {
    marginTop: 4,
    color: shell.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  modalStatsRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  modalRatingNumber: {
    color: shell.textPrimary,
    fontSize: 12,
    fontWeight: '800',
  },
  modalHoldersText: {
    color: shell.textSecondary,
    fontSize: 11,
    fontWeight: '700',
  },
  actionIconRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  actionIconBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surface,
  },
  actionPickerCard: {
    width: '85%',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surfaceMuted,
    padding: 14,
  },
  cancelPickerBtn: {
    marginTop: 5,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surface,
    paddingVertical: 10,
    alignItems: 'center',
  },
  cancelPickerBtnText: {
    color: shell.textPrimary,
    fontWeight: '700',
    fontSize: 13,
  },
  ghostConfirmCard: {
    width: '88%',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surfaceMuted,
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  ghostAvatar: {
    width: 68,
    height: 68,
    borderRadius: 34,
  },
  ghostAvatarFallback: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surfaceMuted,
  },
  ghostConfirmName: {
    marginTop: 10,
    color: shell.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  ghostConfirmNick: {
    marginTop: 2,
    color: shell.textSecondary,
    fontSize: 12,
  },
  ghostConfirmCardName: {
    marginTop: 3,
    color: shell.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  ghostPrivacyText: {
    marginTop: 12,
    color: shell.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 18,
  },
  ghostActionsRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  ghostCallBtn: {
    minWidth: 120,
    borderRadius: 10,
    backgroundColor: shell.textPrimary,
    paddingHorizontal: 18,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostCallBtnText: {
    color: shell.surface,
    fontWeight: '800',
    fontSize: 12,
    letterSpacing: 0.4,
  },
  ghostCancelBtn: {
    minWidth: 120,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.surface,
    paddingHorizontal: 18,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostCancelBtnText: {
    color: shell.textPrimary,
    fontWeight: '800',
    fontSize: 12,
    letterSpacing: 0.4,
  },
  ghostFullBleedGradient: {
    flex: 1,
    width: '100%',
  },
  ghostSafeArea: {
    flex: 1,
    width: '100%',
  },
  ghostLogoTopSlot: {
    alignItems: 'center',
    paddingTop: 4,
    paddingBottom: 4,
  },
  ghostBrandLogoWrap: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: shell.subtleShadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.35,
        shadowRadius: 8,
      },
      android: { elevation: 6 },
      default: {},
    }),
  },
  ghostBrandLogoImage: {
    width: 52,
    height: 52,
  },
  ghostAvatarGlowOuter: {
    marginTop: 4,
    padding: 10,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: 'rgba(248, 220, 150, 0.95)',
    ...Platform.select({
      ios: {
        shadowColor: shell.ctaAccent,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.85,
        shadowRadius: 18,
      },
      android: { elevation: 16 },
      default: {},
    }),
  },
  ghostAvatarGlowInner: {
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 3,
    borderColor: shell.ctaAccent,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: 'rgba(8, 18, 40, 0.45)',
  },
  ghostAvatarImage: {
    width: 112,
    height: 112,
    borderRadius: 56,
  },
  ghostAvatarImageFallback: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: shell.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostActiveBody: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  ghostActiveHeroNick: {
    marginTop: 18,
    color: shell.surface,
    fontSize: 20,
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  ghostActiveStatusLine: {
    marginTop: 8,
    color: 'rgba(255, 255, 255, 0.92)',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  ghostGoldIdentityPill: {
    marginTop: 14,
    maxWidth: '92%',
    backgroundColor: shell.ctaAccent,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: 'rgba(255, 248, 220, 0.55)',
  },
  ghostGoldIdentityPillText: {
    color: shell.textPrimary,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  ghostActiveFullNameSub: {
    marginTop: 10,
    color: 'rgba(255, 255, 255, 0.78)',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  ghostActiveFooterColumn: {
    width: '100%',
    paddingHorizontal: 24,
    paddingBottom: 10,
    alignItems: 'center',
  },
  ghostActivePrivacy: {
    marginTop: 12,
    color: 'rgba(255, 255, 255, 0.62)',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 16,
    paddingHorizontal: 12,
  },
  ghostActiveControlRow: {
    marginTop: 22,
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 360,
    gap: 10,
  },
  ghostControlBtn: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 5,
  },
  ghostControlBtnActive: {
    backgroundColor: 'rgba(197, 160, 101, 0.28)',
    borderColor: 'rgba(248, 220, 150, 0.75)',
  },
  ghostControlText: {
    color: shell.surface,
    fontWeight: '600',
    fontSize: 10,
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  ghostEndBtn: {
    alignSelf: 'stretch',
    width: '100%',
    maxWidth: 400,
    marginTop: 8,
    borderRadius: 14,
    backgroundColor: shell.danger,
    paddingVertical: 15,
    paddingHorizontal: 20,
    alignItems: 'center',
    ...Platform.select({
      ios: {
        shadowColor: shell.danger,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.45,
        shadowRadius: 10,
      },
      android: { elevation: 8 },
      default: {},
    }),
  },
  ghostEndBtnText: {
    color: shell.surface,
    fontWeight: '800',
    fontSize: 15,
    letterSpacing: 0.5,
  },
  ghostIncomingScreenBody: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingBottom: 12,
  },
  ghostIncomingCardFrosted: {
    width: '100%',
    maxWidth: 360,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(197, 160, 101, 0.42)',
    backgroundColor: 'rgba(236, 242, 250, 0.94)',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 22,
    ...Platform.select({
      ios: {
        shadowColor: shell.subtleShadow,
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.2,
        shadowRadius: 24,
      },
      android: { elevation: 12 },
      default: {},
    }),
  },
  ghostIncomingNick: {
    marginTop: 14,
    color: shell.textPrimary,
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
  },
  ghostIncomingTitle: {
    marginTop: 8,
    color: shell.textPrimary,
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  ghostIncomingGoldLine: {
    marginTop: 12,
    color: shell.typeBadgeText,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  ghostIncomingFullNameLine: {
    marginTop: 10,
    color: shell.textPrimary,
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  ghostIncomingActionsRow: {
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: 12,
  },
  ghostIncomingAcceptBtn: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: shell.success,
    paddingVertical: 13,
    alignItems: 'center',
  },
  ghostIncomingAcceptText: {
    color: shell.surface,
    fontWeight: '900',
    fontSize: 15,
    letterSpacing: 0.3,
  },
  ghostIncomingRejectBtn: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: shell.modalBg,
    paddingVertical: 13,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: shell.subtleShadow,
  },
  ghostIncomingRejectText: {
    color: shell.surface,
    fontWeight: '900',
    fontSize: 15,
    letterSpacing: 0.3,
  },
  floatingScanButtonContainer: {
    position: 'absolute',
    bottom: 16,
    right: 20,
    zIndex: 10,
  },
  floatingScanButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: shell.refreshAccent,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: shell.subtleShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  swipeActionsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  swipeActionsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    marginBottom: 10,
    minHeight: 118,
    borderRadius: 15,
    overflow: 'hidden',
  },
  swipeActionCol: {
    width: 78,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    gap: 6,
  },
  swipeActionLabel: {
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  swipeActionButton: {
    width: 64,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: shell.danger,
    marginLeft: 4,
  },
  bottomToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderTopWidth: 1,
  },
});
}
