import { StyleSheet } from "react-native";
import type { AppShellTheme } from "../theme";

export function makeStoriesStyles(shell: AppShellTheme) {
  return StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 14,
  },
  headerWrap: {
    marginBottom: 10,
  },
  title: {
    color: shell.textPrimary,
    fontSize: 24,
    fontFamily: 'Georgia',
    fontWeight: '700',
  },
  subtitle: {
    marginTop: 3,
    color: shell.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  premiumGlowCard: {
    borderRadius: 18,
    padding: 1.2,
    shadowOpacity: 0.36,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  premiumGlowInner: {
    borderRadius: 17,
    overflow: 'hidden',
    borderWidth: 1,
    padding: 14,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusText: {
    color: shell.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  expiryText: {
    marginTop: 6,
    color: shell.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  hintText: {
    marginTop: 8,
    color: shell.textSecondary,
    fontSize: 11,
    lineHeight: 17,
  },
  gridWrap: {
    paddingTop: 14,
    paddingBottom: 96,
  },
  gridItem: {
    width: '25%',
    alignItems: 'center',
    marginBottom: 16,
  },
  gridAvatarRing: {
    width: 78,
    height: 78,
    borderRadius: 39,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridAvatar: {
    width: 68,
    height: 68,
    borderRadius: 34,
  },
  gridAvatarFallback: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: shell.surfaceMuted,
    borderWidth: 1,
    borderColor: shell.border,
  },
  gridCardName: {
    marginTop: 6,
    color: shell.textPrimary,
    fontSize: 10,
    fontWeight: '700',
    maxWidth: 84,
    textAlign: 'center',
  },
  emptyText: {
    textAlign: 'center',
    color: shell.textSecondary,
    fontSize: 12,
    marginTop: 18,
  },
  fabAddStory: {
    position: 'absolute',
    right: 18,
    bottom: 22,
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    shadowOpacity: 0.45,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  fabGlowHalo: {
    position: 'absolute',
    right: 10,
    bottom: 14,
    width: 74,
    height: 74,
    borderRadius: 37,
    shadowOpacity: 0.65,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  loaderWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionsWrap: {
    marginTop: 12,
    gap: 10,
  },
  actionBtn: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
  },
  normalBtn: {
    backgroundColor: shell.storiesNormalBtnBg,
    borderColor: shell.storiesNormalBtnBorder,
  },
  vipBtn: {
    shadowOpacity: 0.24,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  offBtn: {
    backgroundColor: shell.fabText,
    borderColor: shell.border,
  },
  actionBtnText: {
    color: shell.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  actionBtnSub: {
    marginTop: 2,
    color: shell.textSecondary,
    fontSize: 11,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(6,26,42,0.42)',
    justifyContent: 'flex-end',
  },
  createCard: {
    maxHeight: '90%',
    backgroundColor: shell.surfaceMuted,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderColor: shell.border,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 16,
  },
  modalTitle: {
    color: shell.textPrimary,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 10,
  },
  stepTitle: {
    color: shell.textSecondary,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 7,
    marginBottom: 5,
  },
  rowWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  selectorBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.fabText,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  selectorBtnActive: {
    borderColor: shell.textPrimary,
    backgroundColor: shell.surfaceMuted,
  },
  selectorVipBtn: {
    borderColor: 'rgba(212,175,55,0.75)',
    backgroundColor: 'rgba(212,175,55,0.14)',
  },
  exposureHintText: {
    marginTop: 7,
    color: shell.textSecondary,
    fontSize: 11,
    fontWeight: '600',
  },
  selectorText: {
    color: shell.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  pickBtn: {
    borderRadius: 10,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  pickBtnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  fileNameText: {
    marginTop: 5,
    color: shell.textSecondary,
    fontSize: 11,
  },
  selectorListWrap: {
    maxHeight: 110,
    marginBottom: 2,
  },
  listOption: {
    borderRadius: 9,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.fabText,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
  },
  listOptionActive: {
    borderColor: shell.textPrimary,
    backgroundColor: shell.surfaceMuted,
  },
  listOptionText: {
    color: shell.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  emptyCtaText: {
    color: shell.textSecondary,
    fontSize: 11,
    marginBottom: 6,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  cancelBtn: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: shell.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  cancelBtnText: {
    color: shell.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  publishBtn: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: shell.textPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  publishBtnDisabled: {
    backgroundColor: shell.textMuted,
  },
  publishBtnText: {
    color: shell.fabText,
    fontSize: 13,
    fontWeight: '700',
  },
  viewerOverlay: {
    flex: 1,
    backgroundColor: shell.subtleShadow,
    justifyContent: 'center',
  },
  viewerClose: {
    position: 'absolute',
    top: 42,
    right: 16,
    zIndex: 10,
  },
  viewerTopMeta: {
    position: 'absolute',
    top: 44,
    left: 12,
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  viewerMetaText: {
    color: shell.fabText,
    fontSize: 11,
    fontWeight: '700',
  },
  adPanel: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 12,
  },
  adPhoto: {
    width: 240,
    height: 160,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(197,160,101,0.75)',
  },
  adTitle: {
    color: shell.fabText,
    fontSize: 28,
    fontFamily: 'Georgia',
    fontWeight: '700',
    textAlign: 'center',
  },
  adSubtitle: {
    color: shell.surfaceMuted,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
    maxWidth: 320,
  },
  adMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  adMetaText: {
    color: shell.typeBadgeBg,
    fontSize: 12,
    fontWeight: '700',
  },
  adMetaDot: {
    color: shell.ctaAccent,
    fontSize: 12,
    fontWeight: '900',
  },
  adBadge: {
    marginTop: 4,
    color: shell.ctaAccent,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  viewerImage: {
    width: '100%',
    height: '100%',
  },
  viewerDocWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  viewerDocText: {
    color: shell.fabText,
    fontSize: 14,
    fontWeight: '700',
    maxWidth: '85%',
    textAlign: 'center',
  },
  viewerFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 14,
    paddingVertical: 16,
    backgroundColor: 'rgba(0,0,0,0.42)',
  },
  viewerTitle: {
    color: shell.fabText,
    fontSize: 15,
    fontWeight: '800',
  },
  viewerCtaBtn: {
    marginTop: 10,
    borderRadius: 12,
    backgroundColor: shell.textPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: shell.refreshAccent,
  },
  viewerCtaText: {
    color: shell.fabText,
    fontSize: 13,
    fontWeight: '800',
  },
  viewerNavRow: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 8,
  },
  viewerNavBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: shell.surfaceMuted,
    backgroundColor: shell.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
  },
  viewerNavText: {
    color: shell.fabText,
    fontSize: 12,
    fontWeight: '800',
  },
});
}
