import { StyleSheet } from "react-native";
import type { AppShellTheme } from "../app/theme";

export function makeStoriesStyles(shell: AppShellTheme) {
  return StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 14,
    paddingTop: 14,
  },
  headerWrap: {
    marginBottom: 10,
  },
  title: {
    color: shell.textPrimary,
    fontSize: 24,
    fontFamily: 'Georgia',
    fontWeight: '700',
  },
  subtitle: {
    marginTop: 3,
    color: shell.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  premiumGlowCard: {
    borderRadius: 18,
    padding: 1.2,
    shadowOpacity: 0.36,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  premiumGlowInner: {
    borderRadius: 17,
    overflow: 'hidden',
    borderWidth: 1,
    padding: 14,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusText: {
    color: shell.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  expiryText: {
    marginTop: 6,
    color: shell.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  hintText: {
    marginTop: 8,
    color: shell.textSecondary,
    fontSize: 11,
    lineHeight: 17,
  },
  gridWrap: {
    paddingTop: 14,
    paddingBottom: 96,
  },
  gridItem: {
    width: '25%',
    alignItems: 'center',
    marginBottom: 16,
  },
  gridAvatarRing: {
    width: 78,
    height: 78,
    borderRadius: 39,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridAvatar: {
    width: 68,
    height: 68,
    borderRadius: 34,
  },
  gridAvatarFallback: {
    width: 68,
    height: 68,
    borderRadius: 34,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: shell.surfaceMuted,
    borderWidth: 1,
    borderColor: shell.border,
  },
  gridCardName: {
    marginTop: 6,
    color: shell.textPrimary,
    fontSize: 10,
    fontWeight: '700',
    maxWidth: 84,
    textAlign: 'center',
  },
  emptyText: {
    textAlign: 'center',
    color: shell.textSecondary,
    fontSize: 12,
    marginTop: 18,
  },
  fabAddStory: {
    position: 'absolute',
    right: 18,
    bottom: 22,
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    shadowOpacity: 0.45,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  fabGlowHalo: {
    position: 'absolute',
    right: 10,
    bottom: 14,
    width: 74,
    height: 74,
    borderRadius: 37,
    shadowOpacity: 0.65,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  loaderWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionsWrap: {
    marginTop: 12,
    gap: 10,
  },
  actionBtn: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
  },
  normalBtn: {
    backgroundColor: shell.storiesNormalBtnBg,
    borderColor: shell.storiesNormalBtnBorder,
  },
  vipBtn: {
    shadowOpacity: 0.24,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  offBtn: {
    backgroundColor: shell.fabText,
    borderColor: shell.border,
  },
  actionBtnText: {
    color: shell.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  actionBtnSub: {
    marginTop: 2,
    color: shell.textSecondary,
    fontSize: 11,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(6,26,42,0.42)',
    justifyContent: 'flex-end',
  },
  createCard: {
    maxHeight: '90%',
    backgroundColor: shell.surfaceMuted,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderColor: shell.border,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 16,
  },
  modalTitle: {
    color: shell.textPrimary,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 10,
  },
  stepTitle: {
    color: shell.textSecondary,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 7,
    marginBottom: 5,
  },
  rowWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  selectorBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.fabText,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  selectorBtnActive: {
    borderColor: shell.textPrimary,
    backgroundColor: shell.surfaceMuted,
  },
  selectorVipBtn: {
    borderColor: 'rgba(212,175,55,0.75)',
    backgroundColor: 'rgba(212,175,55,0.14)',
  },
  exposureHintText: {
    marginTop: 7,
    color: shell.textSecondary,
    fontSize: 11,
    fontWeight: '600',
  },
  selectorText: {
    color: shell.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  pickBtn: {
    borderRadius: 10,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  pickBtnText: {
    fontSize: 12,
    fontWeight: '700',
  },
  fileNameText: {
    marginTop: 5,
    color: shell.textSecondary,
    fontSize: 11,
  },
  selectorListWrap: {
    maxHeight: 110,
    marginBottom: 2,
  },
  listOption: {
    borderRadius: 9,
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.fabText,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 6,
  },
  listOptionActive: {
    borderColor: shell.textPrimary,
    backgroundColor: shell.surfaceMuted,
  },
  listOptionText: {
    color: shell.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  emptyCtaText: {
    color: shell.textSecondary,
    fontSize: 11,
    marginBottom: 6,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  cancelBtn: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: shell.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  cancelBtnText: {
    color: shell.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  publishBtn: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: shell.textPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  publishBtnDisabled: {
    backgroundColor: shell.textMuted,
  },
  publishBtnText: {
    color: shell.fabText,
    fontSize: 13,
    fontWeight: '700',
  },
  viewerOverlay: {
    flex: 1,
    backgroundColor: '#000000',
  },
  viewerTheaterRoot: {
    flex: 1,
    backgroundColor: '#000000',
  },
  viewerTheaterChrome: {
    paddingHorizontal: 10,
    paddingBottom: 8,
    width: '100%',
  },
  viewerProgressRowTheater: {
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
    width: '100%',
    marginBottom: 8,
  },
  viewerHeaderTheaterRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  viewerHeaderLeft: {
    flex: 1,
    minWidth: 0,
    paddingRight: 6,
  },
  viewerEmitterName: {
    color: 'rgba(245,240,230,0.96)',
    fontSize: 14,
    fontWeight: '800',
  },
  viewerElapsedText: {
    marginTop: 3,
    color: 'rgba(197,160,101,0.92)',
    fontSize: 11,
    fontWeight: '700',
  },
  viewerCloseTheater: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(197,160,101,0.85)',
  },
  viewerStage: {
    flex: 1,
    width: '100%',
    minHeight: 0,
    backgroundColor: '#000000',
  },
  viewerClose: {
    position: 'absolute',
    top: 42,
    right: 16,
    zIndex: 12,
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(197,160,101,0.85)',
  },
  viewerProgressRow: {
    position: 'absolute',
    top: 36,
    left: 10,
    right: 56,
    zIndex: 11,
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
  },
  viewerProgressSegment: {
    flex: 1,
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.18)',
    overflow: 'hidden',
  },
  viewerProgressFill: {
    height: '100%',
    borderRadius: 2,
    backgroundColor: 'rgba(212,175,55,0.95)',
  },
  viewerTapLayer: {
    flex: 1,
    width: '100%',
  },
  viewerTopMeta: {
    position: 'absolute',
    top: 44,
    left: 12,
    zIndex: 10,
    backgroundColor: 'rgba(0,0,0,0.35)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  viewerMetaText: {
    color: shell.fabText,
    fontSize: 11,
    fontWeight: '700',
  },
  adPanel: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    gap: 12,
  },
  adPhoto: {
    width: 240,
    height: 160,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(197,160,101,0.75)',
  },
  adTitle: {
    color: shell.fabText,
    fontSize: 28,
    fontFamily: 'Georgia',
    fontWeight: '700',
    textAlign: 'center',
  },
  adSubtitle: {
    color: shell.surfaceMuted,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
    maxWidth: 320,
  },
  adMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  adMetaText: {
    color: shell.typeBadgeBg,
    fontSize: 12,
    fontWeight: '700',
  },
  adMetaDot: {
    color: shell.ctaAccent,
    fontSize: 12,
    fontWeight: '900',
  },
  adBadge: {
    marginTop: 4,
    color: shell.ctaAccent,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  marketVipRing: {
    flex: 1,
    width: '100%',
    padding: 4,
    borderRadius: 20,
    borderWidth: 2.5,
    borderColor: 'rgba(212,175,55,0.9)',
    backgroundColor: 'rgba(212,175,55,0.12)',
    shadowColor: '#d4af37',
    shadowOpacity: 0.45,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  marketVipPanel: {
    flex: 1,
    width: '100%',
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 22,
    paddingVertical: 20,
    gap: 10,
  },
  marketVipPhoto: {
    width: 220,
    height: 148,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(212,175,55,0.85)',
  },
  marketVipTitle: {
    color: 'rgba(245,240,230,0.98)',
    fontSize: 22,
    fontFamily: 'Georgia',
    fontWeight: '700',
    textAlign: 'center',
  },
  marketVipSubtitle: {
    color: 'rgba(230,220,200,0.88)',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
    maxWidth: 320,
  },
  marketVipMeta: {
    color: shell.ctaAccent,
    fontSize: 12,
    fontWeight: '800',
  },
  marketVipBadge: {
    marginTop: 2,
    color: 'rgba(212,175,55,0.95)',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1,
  },
  viewerImage: {
    width: '100%',
    height: '100%',
  },
  viewerDocWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  viewerDocText: {
    color: shell.fabText,
    fontSize: 14,
    fontWeight: '700',
    maxWidth: '85%',
    textAlign: 'center',
  },
  viewerFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 14,
    paddingVertical: 16,
    backgroundColor: 'rgba(0,0,0,0.42)',
  },
  viewerTitle: {
    color: shell.fabText,
    fontSize: 15,
    fontWeight: '800',
  },
  viewerCtaBtn: {
    marginTop: 10,
    borderRadius: 12,
    backgroundColor: shell.textPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: shell.refreshAccent,
  },
  viewerCtaText: {
    color: shell.fabText,
    fontSize: 13,
    fontWeight: '800',
  },
  viewerNavRow: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 8,
  },
  viewerNavBtn: {
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: shell.surfaceMuted,
    backgroundColor: shell.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
  },
  viewerNavText: {
    color: shell.fabText,
    fontSize: 12,
    fontWeight: '800',
  },
  viewerTextStory: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 28,
    paddingVertical: 48,
    justifyContent: 'center',
  },
  viewerTextStoryBody: {
    color: '#F5F0E6',
    fontSize: 22,
    fontWeight: '600',
    lineHeight: 32,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.75)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  cardPickerCard: {
    maxHeight: '88%',
    backgroundColor: shell.surfaceMuted,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(197,160,101,0.45)',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 14,
  },
  cardPickerTitle: {
    color: shell.textPrimary,
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 4,
  },
  cardPickerSubtitle: {
    color: shell.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 12,
  },
  /** Sin maxWidth aquí: si el contenido no es más ancho que el ScrollView, no hay scroll horizontal. */
  cardPickerCarouselScroll: {
    width: '100%',
    maxHeight: 152,
    flexGrow: 0,
  },
  cardCarouselRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    paddingVertical: 8,
    paddingHorizontal: 4,
    gap: 10,
  },
  cardCarouselItem: {
    width: 200,
    minHeight: 112,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: shell.border,
    paddingVertical: 14,
    paddingHorizontal: 12,
    justifyContent: 'center',
    backgroundColor: shell.fabText,
  },
  cardCarouselItemActive: {
    borderColor: 'rgba(212,175,55,0.95)',
    borderWidth: 2,
    backgroundColor: 'rgba(212,175,55,0.1)',
  },
  cardCarouselName: {
    color: shell.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  cardCarouselMeta: {
    marginTop: 6,
    color: shell.textSecondary,
    fontSize: 11,
    fontWeight: '600',
  },
  publishingAsRow: {
    marginBottom: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(197,160,101,0.35)',
    backgroundColor: 'rgba(212,175,55,0.06)',
  },
  publishingAsLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: shell.textSecondary,
  },
  publishingAsName: {
    marginTop: 3,
    fontSize: 14,
    fontWeight: '800',
  },
  changeAnchorBtn: {
    marginTop: 8,
    alignSelf: 'flex-start',
    paddingVertical: 4,
  },
  changeAnchorText: {
    fontSize: 11,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  vaultMirrorCard: {
    maxHeight: '88%',
    backgroundColor: shell.surfaceMuted,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(197,160,101,0.45)',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 14,
  },
  vaultMirrorTitle: {
    color: shell.textPrimary,
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 4,
  },
  vaultMirrorSubtitle: {
    color: shell.textSecondary,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: 10,
  },
  vaultMirrorGrid: {
    paddingBottom: 8,
  },
  vaultMirrorCell: {
    width: '25%',
    alignItems: 'center',
    marginBottom: 14,
  },
  vaultMirrorIconRing: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: shell.border,
    backgroundColor: shell.fabText,
  },
  vaultMirrorIconRingActive: {
    borderColor: 'rgba(212,175,55,0.95)',
    borderWidth: 2,
    backgroundColor: 'rgba(212,175,55,0.12)',
  },
  vaultMirrorLabel: {
    marginTop: 5,
    color: shell.textPrimary,
    fontSize: 9,
    fontWeight: '700',
    maxWidth: 76,
    textAlign: 'center',
  },
  vaultMirrorActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 6,
  },
  creditHintRow: {
    marginTop: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(212,175,55,0.35)',
    backgroundColor: 'rgba(212,175,55,0.08)',
  },
  creditHintText: {
    color: shell.textPrimary,
    fontSize: 11,
    fontWeight: '700',
  },
  creditHintSub: {
    marginTop: 3,
    color: shell.textSecondary,
    fontSize: 10,
    fontWeight: '600',
  },
  selectedCtaChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(197,160,101,0.5)',
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  selectedCtaChipText: {
    flex: 1,
    color: shell.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  textComposerRoot: {
    flex: 1,
    backgroundColor: '#000',
  },
  textComposerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingTop: 48,
    paddingBottom: 12,
  },
  textComposerTitle: {
    color: 'rgba(245,240,230,0.92)',
    fontSize: 16,
    fontWeight: '800',
  },
  textComposerSwatchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  textComposerSwatchWrap: {
    borderRadius: 16,
  },
  textComposerSwatch: {
    width: 52,
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  textComposerSwatchActive: {
    borderColor: 'rgba(212,175,55,0.95)',
    borderWidth: 2,
  },
  textComposerFontRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  textComposerInput: {
    flex: 1,
    marginHorizontal: 14,
    marginBottom: 24,
    padding: 16,
    borderRadius: 14,
    color: '#F5F0E6',
    fontSize: 20,
    textAlignVertical: 'top',
    textShadowColor: 'rgba(0,0,0,0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  textComposerFooter: {
    paddingHorizontal: 14,
    paddingBottom: 28,
  },
});
}
